# Generated by Django 4.2.4 on 2023-08-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_reservation_date_end_alter_reservation_date_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='disable',
            new_name='enabled',
        ),
    ]
